x-mautic-volumes: &mautic-volumes
  - /mnt/do-volume/mautic/config:/var/www/html/config:z
  - /mnt/do-volume/mautic/logs:/var/www/html/var/logs:z
  - /mnt/do-volume/mautic/media/files:/var/www/html/docroot/media/files:z
  - /mnt/do-volume/mautic/media/images:/var/www/html/docroot/media/images:z
  - /mnt/do-volume/cron:/opt/mautic/cron:z

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /mnt/do-volume/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1G
    networks:
      - default

  mautic_web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:mysql
    ports:
      - ${MAUTIC_PORT:-8001}:80
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
      # Email Configuration (DSN-based for Mautic 6)
      - MAUTIC_MAILER_FROM_NAME=${MAUTIC_MAILER_FROM_NAME:-Método Superare}
      - MAUTIC_MAILER_FROM_EMAIL=${MAUTIC_MAILER_FROM_EMAIL:-noreply@superare.com.br}
      - MAUTIC_MAILER_DSN=${MAUTIC_MAILER_DSN}
    env_file:
      - .mautic_env
    healthcheck:
      test: curl http://localhost
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  mautic_cron:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

  mautic_worker:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:mysql
    volumes: *mautic-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 384M

volumes:
  mysql-data:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
