name: Manual SSL Setup for DOMAIN

on:
  workflow_dispatch:

jobs:
  letsencrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Export DOMAIN to env
        run: echo "DOMAIN=${{ vars.DOMAIN }}" >> $GITHUB_ENV

      - name: Get VPS IP from DigitalOcean
        run: |
          echo "Waiting for droplet to be ready..."
          while : ; do
            echo "."
            sleep 2
            STATUS=$(doctl compute droplet get mautic-vps --format Status --no-header)
            if [ "$STATUS" = "active" ]; then
              IP=$(doctl compute droplet get mautic-vps --format PublicIPv4 --no-header)
              if [ -n "$IP" ]; then
                echo "Droplet is active. IP address: $IP"
                break
              fi
            fi
          done
          echo "ip=$IP" >> $GITHUB_ENV

      - name: Install and run Certbot on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ env.ip }} "
            sudo apt-get update
            sudo apt-get install -y certbot python3-certbot-nginx
            sudo certbot --nginx -n --agree-tos --redirect --email '${{ vars.EMAIL_ADDRESS }}' -d ${{ env.DOMAIN }}
          "
