name: Update Droplet Memory and Swap

on:
  workflow_dispatch:

jobs:
  update-droplet-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Resize Droplet to 2GB
        run: |
          DROPLET_ID=$(doctl compute droplet list --format ID,Name --no-header | grep mautic-vps | awk '{print $1}')
          if [ -z "$DROPLET_ID" ]; then
            echo "Droplet 'mautic-vps' not found!"
            exit 1
          fi
          CURRENT_SIZE=$(doctl compute droplet get $DROPLET_ID --format SizeSlug --no-header)
          if [ "$CURRENT_SIZE" = "s-1vcpu-2gb" ]; then
            echo "Droplet already at 2GB."
          else
            echo "Resizing droplet to 2GB RAM..."
            doctl compute droplet-action resize $DROPLET_ID --size s-1vcpu-2gb --resize-disk
            echo "Resize initiated. Waiting for droplet to be active..."
            while : ; do
              STATUS=$(doctl compute droplet get $DROPLET_ID --format Status --no-header)
              if [ "$STATUS" = "active" ]; then
                break
              fi
              sleep 5
            done
          fi

      - name: Get Droplet IP
        id: get_ip
        run: |
          IP=$(doctl compute droplet get mautic-vps --format PublicIPv4 --no-header)
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Update Swap File to 2G
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.get_ip.outputs.ip }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Updating swap file to 2G..."
            swapoff -a || true
            rm -f /swapfile
            fallocate -l 2G /swapfile
            chmod 600 /swapfile
            mkswap /swapfile
            swapon /swapfile
            grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
            sysctl vm.swappiness=10
            grep -q 'vm.swappiness=10' /etc/sysctl.conf || echo 'vm.swappiness=10' >> /etc/sysctl.conf
            echo "Swap file updated."
            free -h

      - name: Show Memory and Swap Status
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.get_ip.outputs.ip }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Current memory and swap status:"
            free -h
            swapon --show
